#ifndef T3_GAME_CONFIG_H
#define T3_GAME_CONFIG_H

#define GAME_CONFIG_SCREEN_WIDTH 1024
#define GAME_CONFIG_SCREEN_HEIGHT 748
#define GAME_CONFIG_TITLE "My Game"
#define GAME_CONFIG_DEFAULT_BACKGROUND {0, 0, 0, 255}

#define GAME_LOGGING_LEVEL LOG_LEVEL_INFO

#endif //T3_GAME_CONFIG_H
