#ifndef T3_GAME_CONFIG_H
#define T3_GAME_CONFIG_H

#define GAME_RELEASE DEVELOPMENT   //USE DEVELOPMENT OR BUILD
#define GAME_LOGGING_LEVEL LOG_LEVEL_INFO

#define GAME_CONFIG_SCREEN_WIDTH 1024
#define GAME_CONFIG_SCREEN_HEIGHT 748
#define GAME_CONFIG_TITLE "My Game"
#define GAME_CONFIG_DEFAULT_BACKGROUND {0, 0, 0, 255}




#endif //T3_GAME_CONFIG_H
